### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Query the DOM for the racecar
- [x] Listen for keyDown events on document
- [x] Rotate racecar according to keydown event listeners
