### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Give data model x & y coordinates.
- [x] Absolute position the racecar using CSS.
- [x] Set the variable `moveCar` to have a value of `0`
- [x] Implement function `startCar()`
