### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Make a boolean to indicate whether the car is already started.
- [x] Add an event listener for when the space key is pressed.
- [x] Ensure that if user presses the space key a second time, that the interval is cleared.
