### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Make sure car location is being updated
- [x] Change the car's location based on which direction it is facing.
- [x] Remove commented code.
- [x] Remove all console logs.
- [x] Remove unneeded CSS styling.
